baseURL = "https://www.chaidk.me"
languageCode = "en-gb"
title = "Chai Kanchan"
theme = "chaidk"
sectionPagesMenu = "main"

[menu]
[[menu.main]]
identifier = "home"
name = "CDK"
title = "home"
url = "/"
weight = 100

[[menu.main]]
identifier = "development"
name = "Development"
title = "development"
url = "/tags/development"
weight = 0